language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: standin-app
  api_key:
    secure: MNeL57eWQQ7VhriYP0T95/8gxrxwk4mk1v78Juut70J4/ATuYFqa25P42BLAB37DdSFsoScs9pCwmDVhoyEnfj0TpYPXavltU6BLQW57wvaTksuXg9nXRpyC/G+QjbIpws1fIG7oj3OCbHcclpF0fqOzAp35h9UnSWZHIgCjBrgjgSqCu4egD1ICMm4dtrTFGQ9Qv4x/l2DsKqr7zq1APsOaQCXVdnM6wkUJIQ1hTCir29UxhQ7OxG0wuXuxK4Kii4yGUqu81XepUW/HhU0LbeoyTeU8EFpStj32Y58EWP9nBfvpbtOyFojyqeNjNubsIytTaQo11v6mUHY4ktHwX77QOuwZFmlSLFoXBv7Wy8xF6V46GUcz5D+GxiNj68DehWpIz/gpWlmp9A/ildvj1NgqMDUpkiuU8QUAmpo5IwpvwX553C9mA4OdrE8PAs5Nvl4Oa3Ixa2FESOHUx5fJ/rYnotGg8x38Wkie8zDCLxbIQwweqD6dPJ0KHVhxghT2JaH2VHq8AZQSR3R5XuMzgWCNsIIdqbUQ7fy9XCIRuUX9GZXKifn2zitE/vpDehYE4D06XlT4qkChf/M+pYGsIKPD7Ck8pK2LEHIjMpq4Iw+ycRzVes8D7bS51WL7f32b+GceLL+91hIccymNFT4F6s11en256lJZV34PGYMK7Gw=
